name: svf-example

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      XCODE_VERSION: '15.3.0'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # setup the environment 
      - name: mac-setup
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - name: mac-setup-workaround
        if: runner.os == 'macOS'
        run: ln -sfn /Applications/Xcode_${{ env.XCODE_VERSION }}.app /Applications/Xcode.app
      - name: ubuntu-setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install cmake gcc g++ nodejs doxygen graphviz
          
          
      # build current repo
      - name: env-setup
        run: |
          git clone https://github.com/Johanmyst/SVF -b build-fixes
          cd SVF 
          source build.sh
          echo "SVF_DIR=$SVF_DIR" >> $GITHUB_ENV
          echo "LLVM_DIR=$LLVM_DIR" >> $GITHUB_ENV
          echo "Z3_DIR=$Z3_DIR" >> $GITHUB_ENV

      - name: build and ctest
        run: |
          echo "SVF_DIR="$SVF_DIR
          echo "LLVM_DIR="$LLVM_DIR
          echo "Z3_DIR="$Z3_DIR
          cmake .
          make
          ctest -V
